runtime: python312
entrypoint: gunicorn -b :$PORT boredgame.wsgi

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: "boredgame.settings"
  DB_NAME: "boredgame"
  DB_USER: "root"
  DB_PASSWORD: "greed9527"
  DB_HOST: "/cloudsql/boredgame-431808:asia-east1:boredgame"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5